### ISSUE TITLE
Hifiberry 64Bit Alpha won't boot into UI with SocketIO enabled

### ISSUE THREAD

**Issue by coxtor** [willholdoway/hifiberry#32]
See title: Hifiberry 64Bit Alpha won't boot into UI with SocketIO enabled.

- The Integration works
- Hifiberry UI no longer available

**Comment by Guy559** [comment]
Concur with this assessment. Successfully have HiFiBerry reflected within HA but UI no longer accessible via web interface, which precludes ability to conduct OTA software updates (at least to my knowledge).

Would like to be able to utilize HiFiBerry in HA as well as retain access to web UI.

**Comment by schnabel** [comment]
Hi, this has been fixed on the hifiberry side https://github.com/hifiberry/audiocontrol2/issues/39 but I am not sure if it is released yet.

**Comment by coxtor** [comment]
I'm on the latest image and unfortunately the issue persists
